var idfindReplace = stringIDToTypeID( "findReplace" );
    var desc11 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref1 = new ActionReference();
        var idPrpr = charIDToTypeID( "Prpr" );
        var idfindReplace = stringIDToTypeID( "findReplace" );
        ref1.putProperty( idPrpr, idfindReplace );
        var idTxLr = charIDToTypeID( "TxLr" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref1.putEnumerated( idTxLr, idOrdn, idTrgt );
    desc11.putReference( idnull, ref1 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc12 = new ActionDescriptor();
        var idfind = stringIDToTypeID( "find" );
        desc12.putString( idfind, """вася""" );
        var idreplace = stringIDToTypeID( "replace" );
        desc12.putString( idreplace, """лена\rвпередемуйловна""" );
        var idcheckAll = stringIDToTypeID( "checkAll" );
        desc12.putBoolean( idcheckAll, false );
        var idFwd = charIDToTypeID( "Fwd " );
        desc12.putBoolean( idFwd, true );
        var idcaseSensitive = stringIDToTypeID( "caseSensitive" );
        desc12.putBoolean( idcaseSensitive, false );
        var idwholeWord = stringIDToTypeID( "wholeWord" );
        desc12.putBoolean( idwholeWord, false );
        var idignoreAccents = stringIDToTypeID( "ignoreAccents" );
        desc12.putBoolean( idignoreAccents, true );
    var idfindReplace = stringIDToTypeID( "findReplace" );
    desc11.putObject( idUsng, idfindReplace, desc12 );